### ISSUE TITLE
Cakephp 3

### ISSUE THREAD

**Issue by ghost** [LowG33kDev/cakephp-gravatar-plugin#1]
Will this code support ver 3 of cakephp?

**Comment by LowG33kDev** [comment]
Hi, you can see the branch 3.X .

**Comment by ghost** [comment]
Thanks, can this be installed with composer? I didn't see it listed.

**Comment by LowG33kDev** [comment]
You can use `composer require lowg33kdev/cakephp-gravatar-plugin`
https://packagist.org/packages/lowg33kdev/cakephp-gravatar-plugin

**Comment by ghost** [comment]
Thanks, how do I also call the display

**Comment by LowG33kDev** [comment]
You must load the helper on your controller, and after use this on your view:
`echo $this->Gravatar->generate('my-email@test.com`)`
In second parameter, you can add an array with options (you can see options [here](https://github.com/LowG33kDev/cakephp-gravatar-plugin#documentation))
